skydive/routes/auth.py
from skydive.extensions import db
from skydive.models import User
from flask import Blueprint, url_for, redirect, session, \
    abort, request, current_app, flash
from flask_login import login_user, logout_user, current_user
from urllib.parse import urlencode
import secrets
import requests

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@bp.route("/<provider>")
def oauth2_authorize(provider):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    provider_data = current_app.config['OAUTH2_PROVIDERS'].get(provider)
    if provider_data is None:
        abort(404)

    session['oauth2_state'] = secrets.token_urlsafe(16)

    qs = urlencode({
        'client_id': provider_data['client_id'],
        'redirect_uri': url_for('auth.oauth2_callback', provider=provider,
                                _external=True),
        'response_type': 'code',
        'scope': ' '.join(provider_data['scopes']),
        'state': session['oauth2_state'],
    })

    session["next_url"] = request.referrer
    return redirect(provider_data['authorize_url'] + '?' + qs)


@bp.route('/callback/<provider>')
def oauth2_callback(provider):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    provider_data = current_app.config['OAUTH2_PROVIDERS'].get(provider)
    if provider_data is None:
        abort(404)

    if 'error' in request.args:
        for k, v in request.args.items():
            if k.startswith('error'):
                flash(f'{k}: {v}', "error")
        return redirect(url_for('main.home'))

    if request.args['state'] != session.get('oauth2_state'):
        abort(401)

    if 'code' not in request.args:
        abort(401)

    response = requests.post(
        provider_data['token_url'],
        data={'client_id': provider_data['client_id'],
              'client_secret': provider_data['client_secret'],
              'code': request.args['code'],
              'grant_type': 'authorization_code',
              'redirect_uri':
              url_for(
            'auth.oauth2_callback', provider=provider, _external=True), },
        headers={'Accept': 'application/json'})
    if response.status_code != 200:
        abort(401)
    oauth2_token = response.json().get('access_token')
    if not oauth2_token:
        abort(401)

    response = requests.get(
        provider_data['userinfo']['url'],
        headers={'Authorization': 'Bearer ' + oauth2_token,
                 'Accept': 'application/json', })
    if response.status_code != 200:
        abort(401)
    email = provider_data['userinfo']['email'](response.json())

    user = User.query.filter_by(email=email).first()
    if user is None:
        user = User(email=email)
        db.session.add(user)
        db.session.commit()

    login_user(user, remember=True)
    if session.get("next_url"):
        return redirect(session.get("next_url"))
    else:
        return redirect(url_for('main.home'))

skydive/routes/divegenerator.py
from flask import Blueprint, request, flash, render_template
import random

bp = Blueprint('divegen', __name__)


@bp.route("/divegenerator/", methods=["POST", "GET"])
def dive_generator():
    randoms = [(1, r) for r in
               ["A", "B", "C", "D", "E", "F", "G", "H", "J", "K", "L", "M",
                "N", "O", "P", "Q"]]
    a_blocks = [(2, b) for b in ["2", "4", "6", "7", "8", "9", "19", "21"]]
    aa_blocks = [(2, b) for b in
                 ["1", "11", "13", "14", "15", "18", "20", "22"]]
    aaa_blocks = [(2, b) for b in ["3", "5", "10", "12", "16", "17"]]

    full_program = []

    if request.args.get("program"):
        program_string = request.args.get("program")
        full_program = [jump.split('-') for jump in program_string.split('_')]
    elif request.args.get("num_jumps") and request.args.get("class"):
        match request.args["class"].lower():
            case "rookie":
                min_points_per_jump = 3
                pool = randoms
            case "a":
                min_points_per_jump = 3
                pool = randoms + a_blocks
            case "aa":
                min_points_per_jump = 4
                pool = randoms + a_blocks + aa_blocks
            case "aaa":
                min_points_per_jump = 5
                pool = randoms + a_blocks + aa_blocks + aaa_blocks
            case "custom":
                min_points_per_jump = int(request.args["num_points"])
                form_elements = request.args
                prefixes = ("random-", "a_block-",
                            "aa_block-", "aaa_block-")
                pool = [
                    (1, f.split("-")[1].upper())
                    if f.split("-")[1].isalpha() else (2, f.split("-")[1])
                    for f, state in form_elements.items()
                    if state and f.startswith(prefixes)]

        current_pool = pool.copy()

        if sum([p[0] for p in pool]) >= min_points_per_jump:
            for i in range(int(request.args["num_jumps"])):
                program = []

                while sum([p[0] for p in program]) < min_points_per_jump:
                    selected = random.choice(
                        [item for item in current_pool
                            if item not in program])
                    program.append(selected)
                    current_pool.remove(selected)

                    if len(current_pool) <= 0:
                        current_pool = pool.copy()
                full_program.append([p[1] for p in program])
        else:
            flash("Not enough formations to be able to make a program!",
                  "error")

    return render_template(
        "divegenerator.html", program=full_program, randoms=randoms,
        a_blocks=a_blocks, aa_blocks=aa_blocks, aaa_blocks=aaa_blocks)

skydive/routes/logbook.py
from flask import Blueprint, render_template

bp = Blueprint('logbook', __name__, url_prefix="/logbook")


@bp.route('/')
def logbook():
    return render_template("logbook.html")


@bp.route("/import/")
def logbook_import():
    return render_template("logbook_import.html")


@bp.route("/export/")
def logbook_export():
    return render_template("logbook_export.html")

skydive/routes/videos.py
from flask import Blueprint, render_template, abort, send_from_directory, \
    current_app
import os

bp = Blueprint('videos', __name__, url_prefix="/videos")


@bp.route('/')
@bp.route('/<path:subfolder>')
def browse(subfolder=None):
    base_path = current_app.config.get("VIDEO_FOLDER")

    folder_path = os.path.join(
        base_path, subfolder) if subfolder else base_path

    if not os.path.exists(folder_path) or not os.path.commonpath(
            [base_path]) == os.path.commonpath(
            [base_path, folder_path]):
        abort(404, "Folder does not exist or invalid path")

    dirs = [{"name": d, "full_path": os.path.relpath(
        os.path.join(folder_path, d),
        base_path)} for d in os.listdir(folder_path)
        if os.path.isdir(os.path.join(folder_path, d))]

    files = [{"name": f, "full_path": os.path.relpath(
        os.path.join(folder_path, f),
        base_path)} for f in os.listdir(folder_path)
        if os.path.isfile(os.path.join(folder_path, f))]

    dirs = sorted(dirs, key=lambda x: x["name"])
    files = sorted(files, key=lambda x: x["name"])

    return render_template(
        "videos.html", dirs=dirs, files=files, subfolder=subfolder)


@bp.route('/download/<path:filename>')
def download(filename):
    return send_from_directory(
        current_app.config.get("VIDEO_FOLDER"),
        filename)


@bp.route('/play/<path:filename>')
def play(filename):
    return render_template("play.html", file=filename)

skydive/templates/divegenerator.html
{% extends "layout.html" %}
{% block title %}FS4 Generator{% endblock %}
{% block body %}

<h1>FS4 Generator</h1>

<div class="generator-options-wrapper">
  <div class="flex-row">
    <input id="form-random" name="form_type" type="radio" value="random" checked>
    <label class="radio_option" for="form-random">Random</label>
    <input id="form-manual" name="form_type" type="radio"
      value="manual" {{ "checked" if request.args.get("program") }}>
    <label class="radio_option" for="form-manual">Manual</label>
  </div>

  <form id="randomForm" action="" method="get">
    <label for="num_jumps">Number of jumps</label>
    <div class="form-number">
      <button type="button" class="btn btn-decrement" onClick="changeNum('num_jumps', -1)">-</button>
      <input class="form" id="num_jumps" name="num_jumps" type="number"
        value="{{ request.args.get('num_jumps') or '10' }}">
      <button type="button" class="btn btn-increment" onClick="changeNum('num_jumps', 1)">+</button>
    </div>


    <label for="class">Class</label>
    <div class="flex-row mb-0">
      <input id="class-0" name="class" type="radio"
        value="rookie" {{ "checked" if request.args.get("class") == "rookie" }}>
      <label class="radio_option" for="class-0">Rookie</label>
      
      <input id="class-1" name="class" type="radio"
        value="a" {{ "checked" if request.args.get("class") == "a" }}>
      <label class="radio_option" for="class-1">A</label>
      
      <input id="class-2" name="class" type="radio"
        value="aa" {{ "checked" if request.args.get("class") == "aa" }}>
      <label class="radio_option" for="class-2">AA</label>
      
      <input id="class-3" name="class" type="radio"
        value="aaa" {{ "checked" if request.args.get("class") == "aaa" or not request.args.get("class")}}>
      <label class="radio_option" for="class-3">AAA</label>
      
      <input id="class-4" name="class" type="radio"
        value="custom" {{ "checked" if request.args.get("class") == "custom" }}>
      <label class="radio_option" for="class-4">Custom</label>
    </div>
    <div id="dive-options-wrapper">
      <label for="num_points">Min points per jump</label>
      <div class="form-number">
        <button type="button" class="btn btn-decrement" onClick="changeNum('num_points', -1)">-</button>
        <input class="form" id="num_points" name="num_points" type="number" value="4">
        <button type="button" class="btn btn-increment" onClick="changeNum('num_points', 1)">+</button>
      </div>
      <div class="dive-options-flex-wrapper">
        <div class="checkbox-wrapper">
          <input type="checkbox" name="randoms" id="randoms">
          <label for="randoms">RND</label>
          <div class="line"></div>
          {% for _, random in randoms %}
            <input type="checkbox" name="random-{{ random | lower }}"
              id="random-{{ random | lower }}">
            <label for="random-{{ random | lower }}">{{ random }}</label>
          {% endfor %}
        </div>
        <div class="checkbox-wrapper">
          <input type="checkbox" name="a_blocks" id="a_blocks">
          <label for="a_blocks">A</label>
          <div class="line"></div>
          {% for _, block in a_blocks %}
            <input type="checkbox" name="a_block-{{ block | lower }}"
              id="a_block-{{ block | lower }}">
            <label for="a_block-{{ block | lower }}">{{ block }}</label>
          {% endfor %}
        </div>
        <div class="checkbox-wrapper">
        <input type="checkbox" name="aa_blocks" id="aa_blocks">
          <label for="aa_blocks">AA</label>
          <div class="line"></div>
          {% for _, block in aa_blocks %}
            <input type="checkbox" name="aa_block-{{ block | lower }}"
              id="aa_block-{{ block | lower }}">
            <label for="aa_block-{{ block | lower }}">{{ block }}</label>
          {% endfor %}
        </div>
        <div class="checkbox-wrapper">
          <input type="checkbox" name="aaa_blocks" id="aaa_blocks">
          <label for="aaa_blocks">AAA</label>
          <div class="line"></div>
          {% for _, block in aaa_blocks %}
            <input type="checkbox" name="aaa_block-{{ block | lower }}"
              id="aaa_block-{{ block | lower }}">
            <label for="aaa_block-{{ block | lower }}">{{ block }}</label>
          {% endfor %}
        </div>
      </div>
    </div>
    <button type="button" id="dive-options-toggle"
      onClick="toggleDiveCustomForm()">Show options</button>
    <div class="flex-row mb-0">
      <button type="submit" class="btn mb-0">Generate</button>
    </div>
  </form>

  <form id="manualForm" onsubmit="generateUrl(event)" method="get">
    <button type="button" class="btn delete-frame" id="clear-all-btn">Clear All</button>
    <div id="rows-container">
      {% set rows = program if program else range(3) %}
      {% for i in range(rows | length) %}
        <div class="flex-row">
          <div class="list-index">{{ i+1 }}</div>
          {% for j in range(request.args.get("num_points", 5) | int) %}
            <input id="f{{i}}{{j}}" name="f{{i}}{{j}}" type="text" class="form"
              maxlength="2" autocomplete="off"
              value="{{ rows[i][j] if program and j < rows[i]|length else '' }}">
          {% endfor %}
          <button type="button" class="btn mb-0 clear" id="clear-{{i}}" data-action="clear" title="Clear">
            &larr;</button>
          <button type="button" class="btn mb-0 delete" id="delete-{{i}}" data-action="delete" title="Delete">
            &times;</button>
        </div>
      {% endfor %}
    </div>
    <div class="flex-row mb-0">
      <button type="submit" class="btn mb-0">Generate</button>
      <button type="button" class="btn frame mb-0" id="add_row">Add row</button>
    </div>
  </form>
</div>

{% if program %}
  <div class="line"></div>

  <button type="button" onClick="printProgram()" class="btn" id="btn-print">Print</button>

  <div id="full-program">
      {% for jump in program %}
      <div class="jump-program">
        <div class="list-index">{{ loop.index }}</div>
          {% for formation in jump %}
          <div class="img-wrapper">
              <img src="{{ url_for('static', filename='fs4pool/' + (formation | lower) + '.png') }}"
                  alt="{{ formation }}">
          </div>
          {% endfor %}
      </div>
      {% endfor %}
  </div>
{% endif %}

<div id="programModal" class="modal">
  <div class="modal-content">
    <div class="modal-body"></div>
  </div>
</div>


<script src="{{url_for('static', filename='divegenerator.js')}}"></script>
{% endblock %}

skydive/templates/error.html
{% extends "layout.html" %}
{% block body %}

<h3>{{ error.code }}</h3>
{{ error.description }}

{% endblock %}

skydive/templates/index.html
{% extends "layout.html" %}
{% block body %}

<h1>Home</h1>

ping

{% endblock %}

skydive/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}Skydiving - Samuel Rosander{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />
    <link rel="stylesheet" href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" />
    <link rel="icon" sizes="32x32" href="{{ url_for('static', filename='img/favicon-32.png') }}">
    <link rel="icon" sizes="192x192" href="{{ url_for('static', filename='img/favicon-192.png') }}">
    <link rel="manifest" href="{{ url_for('static', filename='site.webmanifest') }}">
    {% block head %}{% endblock %}
  </head>
  <body>
    <div class="wrapper">
      <div class="header">
        <a href="{{ url_for('main.home') }}" class="site-logo">
          <i class='bx bx-cloud'></i>Skydiving</a>
        <button id="menu-button" onClick="toggleMenu()">
          <i class='bx bx-menu'></i>
        </button>
      </div>
      <div class="content">
        <nav id="navbar">
          <ul>
            <li><a href="{{ url_for('main.home') }}"><i class="bx bx-home"></i> Home</a></li>
            <li><a href="{{ url_for('divegen.dive_generator') }}"><i class="bx bx-git-compare"></i> FS4 Generator</a></li>
            <li>
              <button id="logbook-submenu-toggle" type="button" class="nav-arrow-down" onClick="toggleLogbookSubmenu()">&#x25BC;</button>
              <a href="{{ url_for('logbook.logbook') }}"><i class="bx bx-book"></i> Logbook</a>
              <ul id="logbook-submenu">
                <li><a href="{{ url_for('logbook.logbook_import') }}" class="sub-link"><i class="bx bx-cloud-upload"></i> Import</a></li>
                <li><a href="{{ url_for('logbook.logbook_export') }}" class="sub-link"><i class="bx bx-cloud-download"></i> Export</a></li>
              </ul>
            </li>
            <li><a href="{{ url_for('videos.browse') }}"><i class='bx bx-movie-play'></i> Video Archive</a></li>
            <li><a href="https://dzm.burblesoft.com/jmp?dz_id=3373" target="_blank"><i class='bx bx-list-ol'></i> VDZ Manifest</a></li>
          </ul>

          <div class="line"></div>

          {% if current_user.is_authenticated %}
            <div class="user-info">Logged in as
              <div>{{ current_user.email }}</div>
            </div>
            <a href="{{ url_for('auth.logout') }}"><i class="bx bx-log-out"></i> Log out</a>
          {% else %}
            <a href="{{ url_for('auth.oauth2_authorize', provider='google') }}">
              <i class='bx bxl-google'></i> Log in with Google
            </a>
          {% endif %}
        </nav>
        <div class="main-container">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="flash {{ category }}">
                  <span>
                    {{ message | safe}}
                  </span>
                  <span class="flash-close" onClick="dismiss(this)">
                    &times;
                  </span>
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          
          {% block body %}{% endblock %}
        </div>
      </div>
    </div>
    <script src="{{url_for('static', filename='scripts.js')}}"></script>
  </body>
</html>

skydive/templates/logbook.html
{% extends "layout.html" %}
{% block title %}Logbook{% endblock %}
{% block body %}

<h1>Logbook</h1>

Work in progress

{% endblock %}

skydive/templates/logbook_export.html
{% extends "layout.html" %}
{% block title %}Logbook{% endblock %}
{% block body %}

<h1>Export</h1>

<div class="mb-1">Exports your logbook to a .csv file.</div>
<a href="#">Download .csv</a>

{% endblock %}

skydive/templates/logbook_import.html
{% extends "layout.html" %}
{% block title %}Logbook{% endblock %}
{% block body %}

<h1>Import</h1>

<div class="mb-1">Upload a .csv file to import to your logbook.</div>
<a href="#">Download template</a>.

{% endblock %}

skydive/templates/play.html
{% extends "layout.html" %}
{% block title %}Videos{% endblock %}
{% block body %}

<h1>Video Player</h1>

<div class="video-wrapper">
    <h4>{{ file }}</h4>

    <i class='bx bx-subdirectory-left'></i>
    <a href="javascript:window.history.back()">Back</a>


    <video controls id="video-player">
        <source src="{{ url_for('videos.download', filename=file) }}" type="video/mp4">
        Your browser does not support the video tag.
    </video>

</div>
{% endblock %}

skydive/templates/videos.html
{% extends "layout.html" %}
{% block title %}Video Archive{% endblock %}
{% block body %}

<h1>Video Archive</h1>
<div class="video-wrapper">
    <h4>/{{ subfolder or ''}}</h4>
    {% if subfolder %}
        <i class='bx bx-subdirectory-left'></i>
        <a href="{{ url_for('videos.browse', subfolder=subfolder.rsplit('/', 1)[0] if '/' in subfolder else None) }}">
            Back</a>
        <br><br>
    {% endif %}

    <ul>
    {% for dir in dirs %}
        <li>
            <i class='bx bx-folder'></i>
            <a href="{{ url_for('videos.browse', subfolder=dir.full_path) }}">{{ dir.name }}</a>
        </li>
    {% endfor %}
    </ul>

    <div class="video-files-wrapper">
        <ul>
        {% for file in files %}
            <li>
                <i class='bx bx-file-blank'></i>
                <a href="{{ url_for('videos.play', filename=file.full_path) }}">{{ file.name }}</a>
            </li>
        {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}